[project]
name = 'Tokenized-Transportation-Fleet-Electrification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.fleet-verificaiton]
path = 'contracts/fleet-verificaiton.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
